# Generated by Django 6.1.1 on 2026-10-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='show_score_immediately',
            field=models.BooleanField(default=True, help_text="If false, students see 'submitted' but not their score until the exam ends."),
        ),
    ]
