# Generated by Django 6.1.1 on 2026-10-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture. Optional.', null=True, upload_to='avatars/'),
        ),
    ]
